In [5]:
import numpy as np
a=np.array([12,13,14])
b=np.array([15,16,17])
print(a)
print(b)
print(a+b)

[12 13 14]
[15 16 17]
[27 29 31]


In [1]:
l1=[12,13,14]
l2=[44,55,66]
print(l1+l2)


[12, 13, 14, 44, 55, 66]


In [ ]:
make matrix


In [4]:
import numpy as np
arr=np.array([[1,2,3,4,5],[20,30,40,50,60]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [20 30 40 50 60]]
<class 'numpy.ndarray'>


In [ ]:
SLICE METHOD

In [7]:
arr=np.array([10,20,20,33])
print(arr[0:3])
print(arr[:3])

[10 20 20]
[10 20 20]


In [ ]:
SLICING IN TWODARRAY

In [8]:
arr=np.array([[12,13,14,15],[16,17,18,19]])
print(arr[0:2,0:2])

[[12 13]
 [16 17]]


In [ ]:
shape of array

In [13]:
arr=np.array([[10,11,12,13,14],[20,22,33,44,55],[34,33,56,99,88]])
print(np.shape(arr))
print(np.size(arr))

(3, 5)
15


In [ ]:
function 

a.shape=array dimensions
len(A)= length of the day
b.ndim=number of array dimensions
e.size=number of array element
b.dtype=data type of array elelmet
b.astype(int)=convert on array to a differetn type(convert data type just like int to string string to int etc)

In [15]:
import numpy as np

a=[20,30,44,55,88]
arr=np.array(a)
print(arr)
print(arr.shape)

[20 30 44 55 88]
(5,)
