In [ ]:
NumPy Array Copy vs View


In [ ]:
Copy:
=A copy creates a new array that owns its data. It is independent of the original array.
Changes made to the copied array do not affect the original array, and changes to the original do not affect the copy.

In [1]:
import numpy as np

original = np.array([1, 2, 3])
copy = original.copy()
copy[0] = 100

print("Original:", original)  # Output: [1, 2, 3]
print("Copy:", copy)          # Output: [100, 2, 3]

#In this example, modifying the copy does not change the original array.

Original: [1 2 3]
Copy: [100   2   3]


In [ ]:
VIEW
=The view does not own the data and any changes made to the view will affect the original array, 
and any changes made to the original array will affect the view.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[2]=88
print(arr)
print(x)


[ 1  2 88  4  5]
[ 1  2 88  4  5]


In [ ]:
CHAKE IF ARRAY OWNS ITS Data

=As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object.

In [ ]:
How to Check: Using the base Attribute
base attribute: This tells us whether an array shares its data with another array or not.
If base is None, it means the array owns its data (it’s a copy).
If base is not None, it means the array does not own its data (it’s a view).

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
#If base is None, it means the array owns its data (it’s a copy).
#If base is not None, it means the array does not own its data (it’s a view).