In [ ]:
NumPy Data Types
Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


In [ ]:
Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [ ]:
Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.dtype)

int64


In [3]:
import numpy as np
arr=np.array(['banana','apple','orange'])
print(arr.dtype)

<U6


In [ ]:
Creating Arrays With a Defined Data Type

In [4]:
Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#Create an array with data type 4 bytes integer:

In [2]:

import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [3]:
A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

SyntaxError: invalid syntax (4123157005.py, line 1)

In [ ]:
Converting Data Type on Existing Arrays

=The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
The astype() function creates a copy of the array and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer,
or you can use the data type directly like float for float and int for integer.

In [ ]:
#astype() method ka use karke float array ko integer array mein convert kar rahe hain.

In [4]:

Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Change data type from float to integer by using int as parameter value:

In [5]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
#Change data type from integer to boolean:

In [6]:
import numpy as np
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool
