In [ ]:
Installation of NumPy
=If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:
C:\Users\Your Name>pip install numpy


#Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:
import numpy

In [ ]:
Checking NumPy Version
The version string is stored under __version__ attribute.

Example
import numpy as np
print(np.__version__)


Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

ExampleGet your own Python Server

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
output=[1 2 3 4 5]
<class 'numpy.ndarray'>


import numpy as np= Loads the numpy library as np.
arr = np.array([1, 2, 3, 4, 5])= Creates a NumPy array with numbers 1 to 5.
    
print(arr)= Prints the array [1, 2, 3, 4, 5].

print(type(arr))= Shows the type, which is <class 'numpy.ndarray'> (a NumPy array).


In [ ]:
Dimensions in Arrays
=A dimension in arrays is one level of array depth (nested arrays).


In [1]:
0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

Example
Create a 0-D array with value 42

import numpy as np
arr = np.array(42)
print(arr)


42


In [2]:
1-D Arrays
=An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
=A 1D array, or a one-dimensional array, is like a list of numbers arranged in a single row.
These are the most common and basic arrays.

Example
Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:

2-D Arrays
=A 2-D array, or two-dimensional array, is like a grid or table where you have rows and columns.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
3-D array 
=A 3-D array is like a stack of 2-D grids. Imagine a stack of sheets of paper, where each sheet has rows and columns.
When you stack these sheets together, you get a 3-D array.
So, a 3-D array is just multiple 2-D grids piled up to create a layered structure.
    
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
Check Number of Dimensions?
=NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
Creating Arrays:

a = np. array(42)=This creates a single number, 42, which is just a simple value, not really an array in the typical sense.
b = np. array([1, 2, 3, 4, 5])= This creates a 1-D array (a single line of numbers).
c = np. array([[1, 2, 3], [4, 5, 6]])= This creates a 2-D array (a grid with 2 rows and 3 columns).
d = np. array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])=This creates a 3-D array (a stack of 2 grids, each with 2 rows and 3 columns).
Finding the Number of Dimensions (ndim):

a.ndim: This tells you the number of dimensions of array a. Since a is just a single number, it has 0 dimensions.
b.ndim: This tells you the number of dimensions of array b. Since b is a 1-D array, it has 1 dimension.
c.ndim: This tells you the number of dimensions of array c. Since c is a 2-D array, it has 2 dimensions.
d.ndim: This tells you the number of dimensions of array d. Since d is a 3-D array, it has 3 dimensions.