# NumPy Array Iterating

In [ ]:
=Iterating means going through elements one by one.
When you have a 1-D NumPy array (like a list of numbers), you can go through each element using a simple for loop in Python.

# Example:


In [1]:
import numpy as np

# Create a 1-D NumPy array
arr = np.array([10, 20, 30, 40])

# Iterate over the array
for element in arr:
    print(element)


10
20
30
40


In [4]:
import numpy as np
arr=np.array([1,23,44,55,66,77])
for i in arr:
    print(i)

1
23
44
55
66
77


# Here’s what happens:

In [ ]:
The loop will go through the array arr.
It will pick each number (10, then 20, then 30, then 40) and print it.
    
Why is this useful?
It allows you to work with each value in the array, one at a time. You can use it to do things like calculations 
or comparisons with each element.
In simple terms, iterating is just checking each item in the array one after the

# Iterating 2-D Arrays

In [ ]:
What is a 2-D Array?
=A 2-D array in NumPy is like a grid or a table, with rows and columns. Imagine a table with numbers in it, 
where each row and column has a specific position.

# Iterating Over a 2-D Array:

In [ ]:
when we iterated on 2-D array ,we can think of it like going through each row one by one.

# Example:

In [10]:
import numpy as np
arr_2D=np.array([[12,13,15],
                 [20,30,80]])
for row in arr_2D:
    print(row)



[12 13 15]
[20 30 80]


# Iterate on each scalar element of the 2-D array:

In [11]:

import numpy as np
arr=np.array([[1,2,3],[5,6,7]])
for x in arr:
    for y in arr:
        print(y)

[1 2 3]
[5 6 7]
[1 2 3]
[5 6 7]


# Explanation

In [ ]:
First, the outer loop picks the row [1, 2, 3].
The inner loop prints each element: 1, 2, 3.
Then, the outer loop picks the row [4, 5, 6].
The inner loop prints each element: 4, 5, 6.
So the output will be the numbers printed one by one, from top to bottom

# What is nditer()?
=nditer() is a NumPy function that helps you go through each element of an array, regardless of how many dimensions it has (1-D, 2-D, 3-D, etc.).

# Basic Example:

In [12]:
import numpy as np
arr=np.array([[1,2,3],[55,66,77]])
for element in np.nditer(arr):
    print(element)

1
2
3
55
66
77


# How Does It Work?
Creating the Array:
We have a 2-D array like this:

Copy code
[[1, 2, 3],
 [4, 5, 6]]
Using nditer():
np.nditer(arr) creates an iterator that will go through each element of the array.
Iterating Over Elements:

The for loop goes through each element in the array, one by one.
element represents each number in the array, like 1, 2, 3, 4, 5, 6.